### ISSUE TITLE
babel dependencies are missing

### ISSUE THREAD

**Issue by Badisi** [sourcygen/electron-angular-quick-start#1]
I had to add **@babel/core**, **@babel/preset-env** and **babel-loader** to the devDependencies in order to make it work.

But other than that thanks a ton because it is by far the best electron-angular starter that I found ;-)

**Comment by aadiene** [comment]
Sorry for the late response and thank you very much for the feedback. Regarding your issue, those dependencies are normally handled by [electron-webpack](https://webpack.electron.build/). But sadly, the project is now a little bit outdated  and looking for maintainers. That why I put some energy in order to use [electron-forge](https://www.electronforge.io/) from now on.

Feel free to add one ⭐ which will also be very appreciated !

**Comment by Badisi** [comment]
Unfortunately I won't be able to test it anytime soon but really nice upgrade though, well done !

Closing it and adding a star 😉
